Repository NookPost/nookpost-backend, pull requests merged in 2025-02, with the labels that each got.

#9 Added CORS setup for local dev
  Program.cs
Labels: enhancement

#6 Docker Build Action
  .github/workflows/docker.yml
  Dockerfile
Labels: enhancement

#13 Added doxygen config and CSS
  docs/doxygen-awesome-css/doxygen-awesome.css
  doxygen.conf
Labels: documentation

#12 Added models and tables to EF
  Data/DatabaseHandle.cs
  Models/Category.cs
  Models/Post.cs
  Models/User.cs
  Models/UserSettings.cs
Labels: enhancement

#14 Made CI check for warnings fail on found warnings
  Makefile
Labels: enhancement

#20 User settings crud
  ApiEndpoints/UserSettings/GetUserSettings.cs
  ApiEndpoints/UserSettings/PutUserSettings.cs
  ApiSchemas/UserSettings/UserSettingsData.cs
  Data/ModelBuilderExtensions.cs
  Models/Post.cs
  Models/User.cs
  Models/UserSettings.cs
Labels: enhancement

#24 Excluded examples from doxyconf
  doxygen.conf
Labels: documentation

#25 added release action to docker workflow
  .github/workflows/docker.yml
Labels: enhancement

#27 move release action to seperate workflow
  .github/workflows/docker.yml
  .github/workflows/release.yml
Labels: bug

#28 added checkout step to publish workflow
  .github/workflows/release.yml
Labels: bug

#29 try number 4 on fixing automatic releases
  .github/workflows/docker.yml
  .github/workflows/release.yml
Labels: bug

#26 Fixed assignment if not null
  ApiEndpoints/Users/PutUserMe.cs
Labels: bug

#31 Added change password endpoint
  ApiEndpoints/Authentication/ChangePassword.cs
  ApiEndpoints/Authentication/EndpointSetup.cs
  ApiSchemas/Authentication/ChangePassword/PutChangePasswordRequestBody.cs
Labels: enhancement

#32 Fixed doxygen config
  Resources/Icon.png
  Resources/Logo.png
  doxygen.conf
Labels: documentation

#33 Added banner image to posts and requests
  ApiEndpoints/Posts/GetPost.cs
  ApiEndpoints/Posts/GetPostFiltered.cs
  ApiEndpoints/Posts/PostPost.cs
  ApiEndpoints/Posts/PutPost.cs
  ApiSchemas/Posts/PostData.cs
  Models/Post.cs
Labels: enhancement

#35 Added text filter to filter posts endpoint
  ApiEndpoints/Posts/GetPostFiltered.cs
  Data/ModelBuilderExtensions.cs
Labels: enhancement

#36 Remove auth from getall category endpoint
  ApiEndpoints/Categories/EndpointSetup.cs
Labels: enhancement

#40 Added username parameter to Posts Filter Endpoint
  ApiEndpoints/Posts/GetPostFiltered.cs
  Data/ModelBuilderExtensions.cs
Labels: enhancement

#39 Updated paths to objects to comply with REST API spec
  ApiEndpoints/Categories/EndpointSetup.cs
  ApiEndpoints/Posts/EndpointSetup.cs
  ApiEndpoints/UserSettings/EndpointSetup.cs
  ApiEndpoints/Users/EndpointSetup.cs
Labels: enhancement

#41 Added User Display Name to Post GET responses
  ApiEndpoints/Posts/GetPost.cs
  ApiEndpoints/Posts/GetPostFiltered.cs
  ApiSchemas/Posts/GetPost/GetPostResponseBody.cs
  ApiSchemas/Posts/GetPostFiltered/GetPostFilteredPost.cs
  ApiSchemas/Posts/PostGetData.cs
  Data/ModelBuilderExtensions.cs
Labels: enhancement

#44 Fixed API specification not using path parameters
  ApiEndpoints/Posts/EndpointSetup.cs
  ApiEndpoints/Posts/PutPost.cs
  ApiEndpoints/Users/EndpointSetup.cs
  ApiSchemas/Posts/PutPost/PutPostRequestBody.cs
Labels: bug

#49 Added tag and bio to sample data
  Data/ModelBuilderExtensions.cs
Labels: enhancement

#52 Mapped display name correctly
  ApiEndpoints/Users/PostUser.cs
Labels: bug

#50 Changed HTTP status codes where applicable
  ApiEndpoints/Authentication/ChangePassword.cs
  ApiEndpoints/Posts/DeletePost.cs
  ApiEndpoints/Posts/PostPost.cs
  ApiEndpoints/Posts/PutPost.cs
  ApiEndpoints/UserSettings/PutUserSettings.cs
  ApiEndpoints/Users/DeleteUserMe.cs
  ApiEndpoints/Users/PostUser.cs
  ApiEndpoints/Users/PutUserMe.cs
Labels: enhancement
